<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CalcManager\CalcManager.csproj" />
    <ProjectReference Include="..\Calculator.Shared\Calculator.Shared.csproj" />
  </ItemGroup>

</Project>
